### ISSUE TITLE
Submit your week1 report here

### ISSUE THREAD

**Issue by verovilaplana** [mcv-m1-project/deliverables#1]
Submit your week 1 report here (deadline Sunday 16th October 2016).

Publish the link to your public GDrive slides.

**Comment by vcampmany** [comment]
Link to the presentation: [https://docs.google.com/presentation/d/1YI-dFTdTZGyqdljv49JpkAdYKW06LvNDFI4pk5aukj8/edit?usp=sharing](https://docs.google.com/presentation/d/1YI-dFTdTZGyqdljv49JpkAdYKW06LvNDFI4pk5aukj8/edit?usp=sharing)

**Comment by SCLSCL** [comment]
Link to the presentation Team4:
https://docs.google.com/presentation/d/1DjiQ19one561D701V4_dguFaoRAAI0ZGjlJVCw1Phwg/edit?ts=57fe96b4#slide=id.g17a222f976_0_20

**Comment by OnofreMartorell** [comment]
Link to the presentation of Team05:
https://drive.google.com/open?id=1ObZeL_5QdeFbwyMAsEUD7l4g4Axdj-FqTXUqPtySqPI

**Comment by jordi-bird** [comment]
Link of the presentation of Team8:
https://docs.google.com/presentation/d/1pNN0iVISABZNt34qpVeXjprvLbUshE--gWUoK2kLUyo/edit?usp=sharing

**Comment by XeniaSalinas** [comment]
Link of the presentation of Team2:
https://docs.google.com/presentation/d/1vttV49eq2BynF_Cn7JMHtTvZokbmEPhf82T80DyP0kE/edit?usp=sharing

**Comment by bluque** [comment]
Link to the presentation of Team01:
https://docs.google.com/presentation/d/16hmZihOFuyQlCg1n40ocQg1EUbBJlpSJbs1SRXJ1Eno/edit?usp=sharing

**Comment by marccarne** [comment]
Link to the presentation of Team 7:
https://drive.google.com/open?id=1Ri-snlSUNVOOwVMKcNvh0JcvXJx5j0oe6eRFeshevkw

**Comment by LLebronC** [comment]
Link to the presentation of Team 6:
https://docs.google.com/presentation/d/133ELZRCp4MlECa9FBj4koynZL6e90NPOPMCfgOFpATI/edit?usp=sharing
