### ISSUE TITLE
Submit your week2 report here

### ISSUE THREAD

**Issue by rmorros** [mcv-m1-project/deliverables#2]
Submit your week 2 report here (deadline Sunday 23th October 2016).

Publish the link to your public GDrive slides.

**Comment by SCLSCL** [comment]
Report week2 Team 4:

https://docs.google.com/presentation/d/1iktX8mwNcdD7yUJf9zfVSmLYzz-KjOlOgVnAoXuBPsg/edit#slide=id.g17c6790087_1_227

**Comment by LLebronC** [comment]
Report week2 Team 6:
https://docs.google.com/presentation/d/1KmkA4R0iHZCLo0t8L25kL0U-ydo865EnmnVghQO92IA/edit?usp=sharing

**Comment by OnofreMartorell** [comment]
Report week2 Team 5:
https://drive.google.com/open?id=1kDzQ6Px8vvlQq5j530tuUb0KhPSBV09rCBVSzS6rczA

**Comment by gcucurull** [comment]
Report week2 Team 3:
https://docs.google.com/presentation/d/17QtyMUVt4a-5str54fLdagKcL8ck5fM4dvG6fIYhlQk/edit?usp=sharing

**Comment by cristinabustos16** [comment]
Report week2 Team 2
https://docs.google.com/presentation/d/1btnwAJEsIopGd-PJBHMgUMEokHWDlBHudcJ-MzG6ibs/edit?usp=sharing

**Comment by bluque** [comment]
Report Week 2 Team 1:
https://docs.google.com/presentation/d/1_INofHXVmGUQiIQcGZSnPT-0pIzvenrD30Kt3TI3GhQ/edit?usp=sharing

**Comment by MrLeylo** [comment]
Report Week 2 Team 8:
https://docs.google.com/presentation/d/1F_BBPOgoCR8fq8dj_wdDhnYXGOYG5UAUs-dUex_Nano/edit?usp=sharing

**Comment by mgraugal8** [comment]
Report Week 2 Team 7:
https://docs.google.com/presentation/d/1hJIBnki3GYHLLoDVCgdfBVDqSITNU-4JlhgrWaQQo74/pub?start=false&loop=false&delayms=3000
