### ISSUE TITLE
Week 3 - Report

### ISSUE THREAD

**Issue by gcucurull** [mcv-m1-project/deliverables#3]
Team 3 - https://docs.google.com/presentation/d/1nva-hK2QfoE9JM8QakvgDAKokBXBWsvvNztd8eKTzmg/edit#slide=id.g18da3e54e7_0_0

**Comment by JoseLGomez** [comment]
Team 6 - https://docs.google.com/presentation/d/1EsO5fpihhlJ5SrgbQb1oom6xpzJKEtnnEoQWapmnL-A/edit#slide=id.g18dd0ab14a_0_0

**Comment by mgraugal8** [comment]
Team 7 report 3 

https://docs.google.com/presentation/d/1VKnkDgveLjfees0hoNhxZZw8ei2uRKW0XemUihmHiwg/pub?start=false&loop=false&delayms=3000

**Comment by cristinabustos16** [comment]
Team 2 week 3
https://docs.google.com/presentation/d/1GQvyDwRpw2akHJbEznVLO-fJjbb-isFW0IJvJNn7KSA/edit?usp=sharing

**Comment by tpereztorres** [comment]
Team 4 Week 3:

https://docs.google.com/presentation/d/1RkCQ_kKsWaB5bJkA2h7zoJleuVh0SDBs1YOKXX9j368/edit?usp=sharing

**Comment by ArantxaCasanova** [comment]
Team 1 week 3
https://docs.google.com/presentation/d/1GP-lR5pqwUxPC1rV3R74b48T6piR5RlU67p_UvkzNI8/edit?usp=sharing

**Comment by hprop** [comment]
Team 8 Week 3:
https://docs.google.com/presentation/d/1OPNMNTL9PLDucevJIRclRqSu5ilTZ1dZBP1H0f1B5Q4/edit?usp=sharing

**Comment by OnofreMartorell** [comment]
Team 5 week 3:
https://drive.google.com/open?id=10P0t-0ZB51DNpJVqREPS0RVpRXUpuwA6tuSqvkSjsSo
