### ISSUE TITLE
Submit your week4 report here

### ISSUE THREAD

**Issue by rmorros** [mcv-m1-project/deliverables#4]
Submit your week 4 report here (deadline Sunday 6th November 2016).

Publish the link to your public GDrive slides.

**Comment by cristinabustos16** [comment]
Team 2 week 4
https://docs.google.com/presentation/d/1p5r1GmFlcyGJ2djpWJTphyIK4Sz4QV9S4SJ2ob3kKdQ/edit?usp=sharing

**Comment by marccarne** [comment]
Team 7 week 4
[https://docs.google.com/presentation/d/1HdsodUOSz5niE_DaEpGIAHt7TDDnQz8zzcNjQVngLl8/edit?usp=sharing]

**Comment by gcucurull** [comment]
Team 3 - week 4
https://docs.google.com/presentation/d/1n-zn3Q5nisrYSkDIvQXVrA9fYmT4S78gO_GG2JJ4mJQ/edit?usp=sharing

**Comment by OnofreMartorell** [comment]
Team 5 - Week 4
https://drive.google.com/open?id=1B0pEankMhTWi_EmEECOseW3GjyC02QV2JHOT1n7BSJE

**Comment by ArantxaCasanova** [comment]
Team 1 - Week 4
https://docs.google.com/presentation/d/17b2UkOgCwxYDMZrafHrqvY85zO8F8UNqwWjhuYuLSOM

**Comment by LLebronC** [comment]
Team 6 Week 4
https://docs.google.com/presentation/d/1z2gnrIlWMYWOOoEbfY6GOccIGk8QWtoobbS7g72_EOc/edit?usp=sharing

**Comment by tpereztorres** [comment]
Team 4 - Week 4
https://docs.google.com/presentation/d/1TtN_iiUm_nRov5EDi0NqT9SYI2jWwdglX-j1npxqZdE/edit?usp=sharing

**Comment by MrLeylo** [comment]
Team 8 - Week 4
https://docs.google.com/presentation/d/1BCUEIhbv_ZTmVo6C41KJGfaixTN4RkhjGFKMELW-qcg/edit?usp=sharing
