### ISSUE TITLE
Submit your week 5 report here

### ISSUE THREAD

**Issue by rmorros** [mcv-m1-project/deliverables#5]
Submit your week 4 report here (deadline Sunday 13th November 2016).

Publish the link to your public GDrive slides.

**Comment by MrLeylo** [comment]
https://docs.google.com/presentation/d/15nwgTmRi3XHiL93KZaV5vp7qF1FiY0vJjFfk-VrK_1M/edit?usp=sharing

**Comment by MrLeylo** [comment]
Team 8:

https://docs.google.com/presentation/d/15nwgTmRi3XHiL93KZaV5vp7qF1FiY0vJjFfk-VrK_1M/edit?usp=sharing

**Comment by ghost** [comment]
Team 3:

https://docs.google.com/presentation/d/1FWqgQ7thLUmMlLqYn10fU_O_hv0sBsN5xw8OidS2Dck/edit?usp=sharing

**Comment by cristinabustos16** [comment]
Team 2: 
https://docs.google.com/presentation/d/1cwPxOWAa2J4o7iCEXTqlonPurdTdfFikFiXP33NKdRE/edit?usp=sharing

**Comment by LLebronC** [comment]
Team 6:
https://docs.google.com/presentation/d/1XZY_-u90KB4LxD0C1TV_4uLUIKV24WMdZiQBMyOrYNU/edit?usp=sharing

**Comment by OnofreMartorell** [comment]
Team 5:
https://drive.google.com/open?id=1Kra6QiHq92BZOdF7zfwv68N1h4xRr10jyMU2nFaKdVU

**Comment by tpereztorres** [comment]
Team 4:

https://docs.google.com/presentation/d/134oLBUBVRPBdvzMubO9ClBvRtw9qNGuL7DjTdOfrb2M/edit?usp=sharing

**Comment by santiago-puch-giner** [comment]
Team 1:

https://docs.google.com/presentation/d/1ZQIhkIot2UuP7o-Kn1_XTJnZTTpVdteP4Grg3ZxiKvo/edit?usp=sharing

**Comment by vsegura93** [comment]
Team 7: 

https://docs.google.com/presentation/d/1feH6lWAixJ9DTcZkMlHcRHTEdkBR6iIAZGt3SP2givg/pub?start=false&loop=false&delayms=3000&slide=id.g18f4757430_0_0
